version: 2.1

orbs:
  architect: giantswarm/architect@4.28.1

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: node-operator
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-to-quay
          image: "quay.io/giantswarm/node-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-to-aliyun-master
          image: "giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/node-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-to-aliyun-pr
          image: "giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/node-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          filters:
            branches:
              ignore: master
            tags:
              ignore: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog-master
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "node-operator"
          requires:
            - push-to-aliyun-master
            - push-to-quay
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog-pr
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "node-operator"
          requires:
            - push-to-quay
          filters:
            branches:
              ignore: master

      - architect/push-to-app-collection:
          context: architect
          name: push-to-aws-app-collection
          app_name: "node-operator"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-to-app-catalog-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-azure-app-collection
          app_name: "node-operator"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-to-app-catalog-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
