version: 2.1

orbs:
  architect: giantswarm/architect@6.3.2

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: node-operator
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - main
                - master

      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog-master
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          chart: node-operator
          requires:
            - push-to-registries
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog-pr
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          chart: node-operator
          requires:
            - push-to-registries
          filters:
            branches:
              ignore: master
