image:
  registry: quay.io
  name: "giantswarm/node-operator"
  tag: "[[ .Version ]]"

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

Installation:
  V1:
    Registry:
      Domain: quay.io

pod:
  user:
    id: 1000
  group:
    id: 1000

resource:
  deployment:
    replicas: 1
  service:
    port: "8000"
    protocol: "TCP"
