image:
  registry: quay.io
  name: "giantswarm/node-operator"
  tag: "[[ .Version ]]"

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

pod:
  user:
    id: 1000
  group:
    id: 1000

resource:
  deployment:
    replicas: 1
  service:
    port: "8000"
    protocol: "TCP"

registry:
  domain: docker.io

# Add seccomp to pod security context
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
    - ALL
