image:
  registry: quay.io
  name: "giantswarm/node-operator"
  tag: "[[ .Version ]]"

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

provider:
  kind: "aws"

pod:
  user:
    id: 1000
  group:
    id: 1000

resource:
  deployment:
    replicas: 1
  service:
    port: "8000"
    protocol: "TCP"

registry:
  domain: gsoci.azurecr.io

# Add seccomp to pod security context
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL

serviceMonitor:
  enabled: true
  # -- (duration) Prometheus scrape interval.
  interval: "60s"
  # -- (duration) Prometheus scrape timeout.
  scrapeTimeout: "45s"

global:
  podSecurityStandards:
    enforced: false
