apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "resource.default.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  # The node-operator watches NodeConfig CRs and updates their status. It must
  # not be allowed to create these CRs nor delete them. This responsibility is
  # given to other authorities.
  - apiGroups:
      - core.giantswarm.io
    resources:
      - nodeconfigs
    verbs:
      - get
      - list
      - update
      - patch
      - watch
  - apiGroups:
      - core.giantswarm.io
    resources:
      - nodeconfigs/status
    verbs:
      - create
      - patch
      - update
  # The node-operator watches DrainerConfig CRs and updates their status. It
  # must not be allowed to create these CRs nor delete them. This responsibility
  # is given to other authorities.
  - apiGroups:
      - core.giantswarm.io
    resources:
      - drainerconfigs
    verbs:
      - get
      - list
      - update
      - patch
      - watch
  - apiGroups:
      - core.giantswarm.io
    resources:
      - drainerconfigs/status
    verbs:
      - create
      - patch
      - update
  # The node-operator watches secrets in order to create Kubernetes clients for
  # being able to access guest clusters to drain its nodes. It must not be
  # allowed to do anything else than reading secrets.
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
      - clusterrolebindings
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - "/"
      - "/healthz"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource.default.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.default.name" . }}
    namespace: {{ include "resource.default.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "resource.default.name" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "resource.psp.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ include "resource.psp.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource.psp.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.default.name" . }}
    namespace: {{ include "resource.default.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "resource.psp.name" . }}
  apiGroup: rbac.authorization.k8s.io
