apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.resource.service.port }}
    protocol: TCP
    targetPort: http
  selector:
    {{- include "labels.selector" . | nindent 4 }}
