apiVersion: v1
kind: ConfigMap
metadata:
  name: node-operator-configmap
  namespace: {{ .Values.namespace }}
data:
  config.yml: |
    server:
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
