apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resource.default.name }}
  namespace: {{ .Values.resource.default.namespace }}
  labels:
    app: {{ .Values.resource.default.name }}
spec:
  replicas: {{ .Values.resource.deployment.replicas }}
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.resource.default.name }}
  template:
    metadata:
      annotations:
        releasetime: {{ $.Release.Time }}
      labels:
        app: {{ .Values.resource.default.name }}
    spec:
      volumes:
      - name: {{ .Values.resource.configMap.name }}
        configMap:
          name: {{ .Values.resource.configMap.name }}
          items:
          - key: config.yml
            path: config.yml
      serviceAccountName: {{ .Values.resource.default.name }}
      securityContext:
        runAsUser: {{ .Values.pod.user.id }}
        runAsGroup: {{ .Values.pod.group.id }}
      containers:
      - name: node-operator
        image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - daemon
        - --config.dirs=/var/run/node-operator/configmap/
        - --config.files=config
        volumeMounts:
        - name: {{ .Values.resource.configMap.name }}
          mountPath: /var/run/node-operator/configmap/
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
          limits:
            cpu: 250m
            memory: 250Mi
