apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.resource.default.name }}
  namespace: {{ .Values.resource.default.namespace }}
  labels:
    app: {{ .Values.resource.default.name }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: {{ .Values.resource.service.port }}
  selector:
    app: {{ .Values.resource.default.name }}
