//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfig) DeepCopyInto(out *DrainerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfig.
func (in *DrainerConfig) DeepCopy() *DrainerConfig {
	if in == nil {
		return nil
	}
	out := new(DrainerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DrainerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigList) DeepCopyInto(out *DrainerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DrainerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigList.
func (in *DrainerConfigList) DeepCopy() *DrainerConfigList {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DrainerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigSpec) DeepCopyInto(out *DrainerConfigSpec) {
	*out = *in
	out.Guest = in.Guest
	out.VersionBundle = in.VersionBundle
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigSpec.
func (in *DrainerConfigSpec) DeepCopy() *DrainerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigSpecGuest) DeepCopyInto(out *DrainerConfigSpecGuest) {
	*out = *in
	out.Cluster = in.Cluster
	out.Node = in.Node
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigSpecGuest.
func (in *DrainerConfigSpecGuest) DeepCopy() *DrainerConfigSpecGuest {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigSpecGuest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigSpecGuestCluster) DeepCopyInto(out *DrainerConfigSpecGuestCluster) {
	*out = *in
	out.API = in.API
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigSpecGuestCluster.
func (in *DrainerConfigSpecGuestCluster) DeepCopy() *DrainerConfigSpecGuestCluster {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigSpecGuestCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigSpecGuestClusterAPI) DeepCopyInto(out *DrainerConfigSpecGuestClusterAPI) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigSpecGuestClusterAPI.
func (in *DrainerConfigSpecGuestClusterAPI) DeepCopy() *DrainerConfigSpecGuestClusterAPI {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigSpecGuestClusterAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigSpecGuestNode) DeepCopyInto(out *DrainerConfigSpecGuestNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigSpecGuestNode.
func (in *DrainerConfigSpecGuestNode) DeepCopy() *DrainerConfigSpecGuestNode {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigSpecGuestNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigSpecVersionBundle) DeepCopyInto(out *DrainerConfigSpecVersionBundle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigSpecVersionBundle.
func (in *DrainerConfigSpecVersionBundle) DeepCopy() *DrainerConfigSpecVersionBundle {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigSpecVersionBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigStatus) DeepCopyInto(out *DrainerConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]DrainerConfigStatusCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigStatus.
func (in *DrainerConfigStatus) DeepCopy() *DrainerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigStatusCondition) DeepCopyInto(out *DrainerConfigStatusCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigStatusCondition.
func (in *DrainerConfigStatusCondition) DeepCopy() *DrainerConfigStatusCondition {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigStatusCondition)
	in.DeepCopyInto(out)
	return out
}
